---
title: "Simple simulation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Define data

```{r}
def <- defData(varname = "C", formula = .4, dist = "binary")
def <- defData(def,varname = "A", formula = "-2 + 2*C", variance = 2, dist = "normal")
def <- defData(def, varname = "Y", formula = "5 + 2*C + 2*A", variance = 2, dist = "normal")

def
```

Generate data

```{r}
set.seed(383743)
DT <- genData(1000, def)

DT
```

Look at data

```{r}
p <- ggplot(data = DT, aes(y = Y, x= A)) +
  geom_point(aes(color = factor(C)), size = 1) +
  theme(panel.grid.minor = element_blank()) +
  scale_color_manual(values = c("#CC6677","#4477AA"))
p
```

Fit models

```{r}
lmfit1 <- lm(Y~A, data = DT)
summary(lmfit1)
```

```{r}
lmfit2 <- lm(Y~A + C , data = DT)
summary(lmfit2)
```

Look at model fits

```{r}
ggplot(data = DT, aes(y = Y, x= A)) +
  geom_point(size = 1) +
  theme(panel.grid.minor = element_blank()) +
  geom_abline(intercept = coef(lmfit1)[1], 
                slope = coef(lmfit1)[2],
                size = 1)
```

Correct lines:

```{r}
p + 
  geom_abline(intercept = coef(lmfit1)[1], 
              slope = coef(lmfit1)[2],
              size = 1) +
  geom_abline(intercept = coef(lmfit2)[1], 
              slope = coef(lmfit2)[2],
              color = "#CC6677", size = 1) +
  geom_abline(intercept = coef(lmfit2)[1] + coef(lmfit2)[3], 
              slope = coef(lmfit2)[2],
              color = "#4477AA", size = 1)
```